### PR TITLE
Update CheckOutSheet.ods

### LINKED ISSUE #5: Test 5
Yet another test to see if I can get issues and projects talking automatically.

### PR DESCRIPTION
**Pull request by FJCC**
Checking out the first three sub-documents of Getting Started. These include Jean's changes and suggestions

### CODE REVIEW

**Review by orcmid — CHANGES_REQUESTED** [review]
This commit has not been specified against a known branch.  

There needs to be some clarification on how binary files in pushes can be opened for review.

Also, if the intention is to create a branch, there seems to be something missing.
oooDoc-2012-02-08-0951-GettingStartedPull-FC

**Review by orcmid — COMMENTED** [review]
It appears that the .ods file is not downloadable from the pull request, so meaningful review (although probably not needed) is not possible.

This could be either a GitHub or a browser or a permissions problem.  Need to sort that out.

**Comment by orcmid** [comment]
I did manage to synchronize after figuring out that the Review folder is on branch Getting-Started-Guide.

I recommend that the CheckOutSheet.ods file be changed to a table in Markdown (i.e. CheckOutStatus.md).  This will allow viewing in a browser and also show changes and diffs about them.

**Comment by knmc** [comment]
On 2021-02-08 at 12:04, FJCC < notifications@github.com > wrote:




You can download files without a PR. Just bookmark
https://github.com/apache/openoffice-docs/tree/Getting-Sarted-Guide and click
the go to file button click the file you want and click the  download button
at the bottom right of the screen. Do not grab the .ODM that was how the
chapter files were created and can be used as the Full Book to transfer to the
mwiki. I cannot Merge that PR yet. I use Authy for the 2 step verification and
my phone is in the middle of  a massive update. I will do it as soon as I can




Regards

Keith


Checking out the first three sub-documents of Getting Started. These include
Jean's changes and suggestions.


You can view, comment on, or merge this pull request online at:

  https://github.com/apache/openoffice-docs/pull/1

Commit Summary
Update CheckOutSheet.ods

File Changes
M Review/CheckOutSheet.ods (0)

Patch Links:
https://github.com/apache/openoffice-docs/pull/1.patch
https://github.com/apache/openoffice-docs/pull/1.diff

**Comment by knmc** [comment]
On 2021-02-08 at 13:33, Dennis E. Hamilton < notifications@github.com > wrote:





I did manage to synchronize after figuring out that the Review folder is on
branch Getting-Started-Guide.

I recommend that the CheckOutSheet.ods file be changed to a table in Markdown
(i.e. CheckOutStatus.md).  This will allow viewing in a browser and also show
changes and diffs about them.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly,  view it on GitHub , or  unsubscribe .




I like the idea the idea of doing the check out sheet in markdown I will start
that now, Just wont be able to push it until my phone is done with its update.




Regards

Keith

**Comment by knmc** [comment]
Looks good, merging .

**Review by knmc — APPROVED** [review]

**Pull request merged**
